<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20260206194056 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE items_group (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT DEFAULT 0 NOT NULL COMMENT \'公司ID\', regionauth_id BIGINT DEFAULT 0 NOT NULL COMMENT \'地区ID\', group_key VARCHAR(50) DEFAULT \'\' NOT NULL COMMENT \'分组唯一码\', remark VARCHAR(100) DEFAULT \'\' NOT NULL COMMENT \'备注\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_group_key (group_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商品分组\' ');
        $this->addSql('CREATE TABLE items_group_rel_item (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT DEFAULT 0 NOT NULL COMMENT \'公司ID\', regionauth_id BIGINT DEFAULT 0 NOT NULL COMMENT \'地区ID\', group_id BIGINT DEFAULT 0 NOT NULL COMMENT \'分组ID\', group_type VARCHAR(50) DEFAULT \'\' NOT NULL COMMENT \'分组类型(coupon, widget, marketing)\', item_id BIGINT DEFAULT 0 NOT NULL COMMENT \'sku-id\', goods_id BIGINT DEFAULT 0 NOT NULL COMMENT \'spu-id\', is_del BIGINT DEFAULT 0 NOT NULL COMMENT \'是否删除\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_goods_id (goods_id), INDEX idx_group_id (group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商品分组关联商品\' ');
        $this->addSql('CREATE TABLE kujiale_designer_goods (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', good_id VARCHAR(128) NOT NULL COMMENT \'渲染图ID\', dimensions VARCHAR(32) NOT NULL COMMENT \'尺寸\', description VARCHAR(255) NOT NULL COMMENT \'描述\', brand_good_code VARCHAR(128) NOT NULL COMMENT \'商品编码\', brand_good_name VARCHAR(128) NOT NULL COMMENT \'商品名称\', brand_id VARCHAR(32) NOT NULL COMMENT \'品牌id\', brand_name VARCHAR(128) NOT NULL COMMENT \'品牌名称\', series_tag_id VARCHAR(32) NOT NULL COMMENT \'系列id\', series_tag_name VARCHAR(128) NOT NULL COMMENT \'系列名称\', product_number VARCHAR(32) NOT NULL COMMENT \'型号\', customer_texture VARCHAR(64) NOT NULL COMMENT \'材质\', buy_link VARCHAR(255) NOT NULL COMMENT \'购买链接\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_good_id (good_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_goods_rel (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', pic_id VARCHAR(255) NOT NULL COMMENT \'渲染图ID\', obs_brand_good_id VARCHAR(128) NOT NULL COMMENT \'商品ID\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_brand_good_id (obs_brand_good_id), INDEX idx_pic_id (pic_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_tags (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', tag_category_id VARCHAR(255) NOT NULL COMMENT \'标签类目id\', tag_category_name VARCHAR(255) DEFAULT NULL COMMENT \'标签类目名\', type INT DEFAULT NULL COMMENT \'类型\', is_multiple_selected INT DEFAULT NULL COMMENT \'是否支持多选\', is_disabled INT DEFAULT NULL COMMENT \'是否禁用\', tag_id VARCHAR(255) DEFAULT NULL COMMENT \'标签id\', tag_name VARCHAR(255) DEFAULT NULL COMMENT \'标签名称\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_category_id (tag_category_id), INDEX idx_tag_id (tag_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_works (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', design_name VARCHAR(255) NOT NULL COMMENT \'方案名称\', cover_pic TEXT DEFAULT NULL COMMENT \'方案封面\', is_origin BIGINT DEFAULT NULL COMMENT \'是否原创\', is_excellent BIGINT DEFAULT NULL COMMENT \'是否优秀\', is_real_excellent BIGINT DEFAULT NULL COMMENT \'是否优秀\', is_top BIGINT DEFAULT NULL COMMENT \'是否置顶\', design_id VARCHAR(255) DEFAULT NULL COMMENT \'方案ID\', plan_id VARCHAR(255) DEFAULT NULL COMMENT \'户型ID\', comm_name VARCHAR(255) DEFAULT NULL COMMENT \'小区\', city VARCHAR(255) DEFAULT NULL COMMENT \'城市\', name VARCHAR(255) DEFAULT NULL COMMENT \'户型名称\', tag_id VARCHAR(255) DEFAULT NULL COMMENT \'方案分类id\', design_pano_url VARCHAR(255) DEFAULT NULL COMMENT \'全景漫游url\', user_avatar VARCHAR(255) DEFAULT NULL COMMENT \'用户头像\', email VARCHAR(255) DEFAULT NULL COMMENT \'邮箱\', user_name VARCHAR(255) DEFAULT NULL COMMENT \'用户名\', user_id VARCHAR(255) DEFAULT NULL COMMENT \'用户id\', organization_id VARCHAR(255) DEFAULT NULL COMMENT \'组织id\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', view_count INT DEFAULT NULL COMMENT \'浏览量\', like_count INT DEFAULT NULL COMMENT \'点赞数\', ku_created INT DEFAULT NULL COMMENT \'方案更新时间\', INDEX idx_design_id (design_id), INDEX idx_user_id (user_id), INDEX idx_plan_id (plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_works_item_rel (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', item_id BIGINT NOT NULL COMMENT \'商品ID\', design_id VARCHAR(255) NOT NULL COMMENT \'设计ID\', goods_bn VARCHAR(255) DEFAULT NULL COMMENT \'SPU货号\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_item_id (item_id), INDEX idx_design_id (design_id), INDEX idx_goods_bn (goods_bn), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'设计师作品与商品绑定关系表\' ');
        $this->addSql('CREATE TABLE kujiale_designer_works_level (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', design_id VARCHAR(255) NOT NULL COMMENT \'方案id\', plan_id VARCHAR(255) DEFAULT NULL COMMENT \'户型ID\', spec_name VARCHAR(255) DEFAULT NULL COMMENT \'户型的房型\', src_area VARCHAR(255) DEFAULT NULL COMMENT \'户型的建筑面积\', area VARCHAR(255) DEFAULT NULL COMMENT \'户型的套内建筑面积\', real_area VARCHAR(255) DEFAULT NULL COMMENT \'户型的套内面积\', plan_pic TEXT DEFAULT NULL COMMENT \'户型图的URL\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_design_id (design_id), INDEX idx_plan_id (plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_works_like (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', design_id VARCHAR(255) NOT NULL COMMENT \'方案id\', plan_id VARCHAR(255) DEFAULT NULL COMMENT \'户型ID\', user_id INT DEFAULT NULL COMMENT \'点赞用户id\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_design_id (design_id), INDEX idx_user_id (user_id), INDEX idx_plan_id (plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_works_pic (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', pic_id VARCHAR(255) NOT NULL COMMENT \'渲染图ID\', pic_type VARCHAR(255) DEFAULT NULL COMMENT \'渲染图类型。0表示普通渲染图，1表示全景图，3表示俯视图\', pic_detail_type BIGINT DEFAULT NULL COMMENT \'渲染图类型细分\', room_name VARCHAR(255) DEFAULT NULL COMMENT \'渲染图所属房间的名字\', img VARCHAR(255) DEFAULT NULL COMMENT \'渲染图URL\', pano_link VARCHAR(255) DEFAULT NULL COMMENT \'全景图的链接地址\', design_id VARCHAR(255) DEFAULT NULL COMMENT \'方案ID\', plan_id VARCHAR(255) DEFAULT NULL COMMENT \'户型ID\', level VARCHAR(255) DEFAULT NULL COMMENT \'渲染图所在房间的楼层信息，正为地上，负为地下室，不存在0层\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_design_id (design_id), INDEX idx_plan_id (plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_works_rel_cities (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', design_id VARCHAR(255) NOT NULL COMMENT \'方案id\', plan_id VARCHAR(255) DEFAULT NULL COMMENT \'户型ID\', city_id INT NOT NULL COMMENT \'城市ID\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_design_id (design_id), INDEX idx_plan_id (plan_id), INDEX idx_city_id (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kujiale_designer_works_rel_tags (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', tag_category_id VARCHAR(255) NOT NULL COMMENT \'标签类目id\', tag_category_name VARCHAR(255) DEFAULT NULL COMMENT \'标签类目名\', tag_id VARCHAR(255) DEFAULT NULL COMMENT \'标签id\', tag_name VARCHAR(255) DEFAULT NULL COMMENT \'标签名称\', design_id VARCHAR(255) NOT NULL COMMENT \'方案id\', plan_id VARCHAR(255) DEFAULT NULL COMMENT \'户型ID\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_design_id (design_id), INDEX idx_category_id (tag_category_id), INDEX idx_plan_id (plan_id), INDEX idx_tag_id (tag_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_segment_rules (rule_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'规则id\', company_id BIGINT NOT NULL COMMENT \'公司id\', distributor_id BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'分销商id\', rule_name VARCHAR(100) NOT NULL COMMENT \'规则名称（分群标签名称）\', description LONGTEXT DEFAULT NULL COMMENT \'人群说明\', rule_config LONGTEXT NOT NULL COMMENT \'规则配置（层级结构，JSON格式存储）\', tag_ids LONGTEXT DEFAULT NULL COMMENT \'关联的标签ID数组（JSON格式）\', status SMALLINT DEFAULT 1 NOT NULL COMMENT \'状态：0=禁用，1=启用\', created bigint NOT NULL, updated bigint NOT NULL, INDEX idx_company_distributor (company_id, distributor_id), INDEX idx_status (status), INDEX idx_created (created), PRIMARY KEY(rule_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'人群规则表\' ');
        $this->addSql('CREATE TABLE members_tag_group_rel (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'主键ID\', group_id BIGINT NOT NULL COMMENT \'标签组ID\', tag_id BIGINT NOT NULL COMMENT \'标签ID\', company_id BIGINT NOT NULL COMMENT \'公司ID\', distributor_id BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'分销商id\', created bigint NOT NULL, INDEX idx_group_id (group_id), INDEX idx_tag_id (tag_id), INDEX idx_company_distributor (company_id, distributor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'会员标签组与标签关系表\' ');
        $this->addSql('CREATE TABLE members_tag_groups (group_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'标签组ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', group_name VARCHAR(100) NOT NULL COMMENT \'标签组名称\', description VARCHAR(255) DEFAULT NULL COMMENT \'描述\', distributor_id BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'分销商id\', wechat_group_id VARCHAR(100) DEFAULT NULL COMMENT \'企业微信标签组ID\', created bigint NOT NULL, updated bigint NOT NULL, INDEX idx_company_id (company_id), INDEX idx_distributor_id (distributor_id), PRIMARY KEY(group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'会员标签组\' ');
        $this->addSql('CREATE TABLE pages_ad_place (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'设置id\', company_id BIGINT NOT NULL COMMENT \'公司id\', regionauth_id BIGINT DEFAULT 0 NOT NULL COMMENT \'区域id\', use_bound INT DEFAULT 0 COMMENT \'适用范围: 0:全部,1:指定店铺\', ad_type VARCHAR(20) NOT NULL COMMENT \'广告类型：弹窗=>popup，轮播图=>carousel\', name VARCHAR(100) NOT NULL COMMENT \'广告位名称\', pages VARCHAR(30) NOT NULL COMMENT \'关联页面\', start_time BIGINT NOT NULL COMMENT \'开始时间\', end_time BIGINT NOT NULL COMMENT \'结束时间\', setting LONGTEXT DEFAULT NULL COMMENT \'设置\', auto_play INT DEFAULT 0 NOT NULL COMMENT \'自动播放\', play_interval INT DEFAULT 3 NOT NULL COMMENT \'播放间隔时间\', auto_close INT DEFAULT 0 NOT NULL COMMENT \'自动关闭\', close_delay INT DEFAULT 10 NOT NULL COMMENT \'关闭延迟时间\', source_id BIGINT DEFAULT 0 NOT NULL COMMENT \'添加者ID: 如店铺ID\', created INT NOT NULL, updated INT DEFAULT NULL, audit_status VARCHAR(255) DEFAULT \'submitting\' NOT NULL COMMENT \'审核状态 submitting待提交 processing审核中 approved成功 rejected审核拒绝\', audit_remark VARCHAR(255) DEFAULT NULL COMMENT \'审核备注\', sort INT DEFAULT 0 NOT NULL COMMENT \'排序\', tracking_code VARCHAR(100) DEFAULT NULL COMMENT \'埋点上报参数\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'广告位设置\' ');
        $this->addSql('CREATE TABLE pages_ad_place_rel_distributors (company_id BIGINT NOT NULL COMMENT \'公司id\', ad_place_id BIGINT NOT NULL COMMENT \'广告位id\', distributor_id BIGINT NOT NULL COMMENT \'店铺id\', PRIMARY KEY(company_id, ad_place_id, distributor_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'广告位与店铺关联表\' ');
        $this->addSql('CREATE TABLE pages_ad_place_rel_member_tags (company_id BIGINT NOT NULL COMMENT \'公司id\', ad_place_id BIGINT NOT NULL COMMENT \'广告位id\', tag_id BIGINT NOT NULL COMMENT \'人群标签id\', PRIMARY KEY(company_id, ad_place_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'广告位与人群标签关联表\' ');
        $this->addSql('CREATE TABLE pages_side_bar (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'设置id\', company_id BIGINT NOT NULL COMMENT \'公司id\', regionauth_id BIGINT DEFAULT 0 NOT NULL COMMENT \'区域id\', name VARCHAR(100) NOT NULL COMMENT \'名称\', pages VARCHAR(100) NOT NULL COMMENT \'关联页面\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否禁用\', setting LONGTEXT DEFAULT NULL COMMENT \'设置\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'侧边栏设置\' ');
        $this->addSql('ALTER TABLE aftersales_detail CHANGE refunded_num refunded_num INT UNSIGNED DEFAULT 0 COMMENT \'实际入库数量\'');
        $this->addSql('ALTER TABLE aftersales_refund CHANGE freight freight INT UNSIGNED DEFAULT 0 COMMENT \'退款运费，根据freight_type存储现金（分）或积分值\'');
        $this->addSql('ALTER TABLE business_rep_user CHANGE create_time create_time bigint NOT NULL');
        $this->addSql('ALTER TABLE common_lang_mod_ar CHANGE data_id data_id BIGINT NOT NULL COMMENT \'业务id字段\'');
        $this->addSql('ALTER TABLE common_lang_mod_cn CHANGE data_id data_id BIGINT NOT NULL COMMENT \'业务id字段\'');
        $this->addSql('ALTER TABLE common_lang_mod_en CHANGE data_id data_id BIGINT NOT NULL COMMENT \'业务id字段\'');
        $this->addSql('ALTER TABLE community_activity CHANGE activity_status activity_status VARCHAR(255) NOT NULL COMMENT \'活动状态 private私有 public公开 protected隐藏 success确认成团 fail成团失败\'');
        $this->addSql('ALTER TABLE distribution_distributor ADD first_letter VARCHAR(5) DEFAULT \'\' NOT NULL COMMENT \'店铺名称首字母\'');
        $this->addSql('ALTER TABLE items_category ADD regionauth_id BIGINT DEFAULT 0 NOT NULL COMMENT \'地区ID\', CHANGE invoice_tax_rate_id invoice_tax_rate_id BIGINT DEFAULT NULL COMMENT \'发票税率ID\', CHANGE invoice_tax_rate invoice_tax_rate VARCHAR(16) DEFAULT NULL COMMENT \'发票税率\'');
        $this->addSql('ALTER TABLE kaquan_discount_cards ADD coupon_type VARCHAR(10) DEFAULT \'mall\' NOT NULL COMMENT \'券类型。mall:商城券;guide:导购专属券\', ADD guide_issue_quantity INT DEFAULT 0 NOT NULL COMMENT \'导购发放数量\'');
        $this->addSql('ALTER TABLE kaquan_user_discount ADD salesperson_code VARCHAR(100) DEFAULT NULL COMMENT \'导购编号(employee_number/work_userid)\', CHANGE card_id card_id BIGINT NOT NULL COMMENT \'微信用户领取的卡券 id \'');
        $this->addSql('CREATE INDEX idx_salesperson_code ON kaquan_user_discount (salesperson_code)');
        $this->addSql('ALTER TABLE members ADD reg_distributor INT DEFAULT 0 COMMENT \'注册时的分销商ID\', ADD reg_salesperson VARCHAR(100) DEFAULT NULL COMMENT \'注册时的导购ID\', ADD op_distributor INT DEFAULT 0 COMMENT \'作为分配的店铺ID\', ADD fp_salesperson VARCHAR(100) DEFAULT NULL COMMENT \'分配的导购员工编号(employee_number/work_userid)\', ADD has_fp TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否有分配导购\', ADD is_become_friend TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否已加为好友。0:否；1:是\', CHANGE created created bigint NOT NULL, CHANGE updated updated bigint NOT NULL');
        $this->addSql('ALTER TABLE members_tags ADD wechat_tag_id VARCHAR(100) DEFAULT NULL COMMENT \'企业微信标签ID\'');
        $this->addSql('ALTER TABLE multi_lang_mod CHANGE data_id data_id BIGINT NOT NULL COMMENT \'业务id字段\'');
        $this->addSql('ALTER TABLE orders_normal_orders_items CHANGE is_invoice is_invoice INT DEFAULT 0 NOT NULL COMMENT \'是否开票,0否 1已开票 2开票中 3红冲\'');
        $this->addSql('ALTER TABLE pages_open_screen_ad ADD start_time BIGINT NOT NULL COMMENT \'开始时间\', ADD end_time BIGINT NOT NULL COMMENT \'结束时间\'');
        $this->addSql('ALTER TABLE pages_template ADD regionauth_id BIGINT DEFAULT 0 COMMENT \'区域id\', CHANGE weapp_pages weapp_pages VARCHAR(255) DEFAULT \'index\' COMMENT \'模版页面:index-首页 distributor_index-门店首页\', CHANGE lang lang VARCHAR(255) DEFAULT NULL COMMENT \'模版语言\'');
        $this->addSql('ALTER TABLE pages_template_set ADD regionauth_id BIGINT DEFAULT 0 COMMENT \'区域id\'');
        $this->addSql('ALTER TABLE popularize_promoter_identity CHANGE is_default is_default INT NOT NULL COMMENT \'是否为默认\'');
        $this->addSql('ALTER TABLE promotions_package_item CHANGE is_show is_show TINYINT(1) DEFAULT NULL COMMENT \'列表页是否显示\'');
        $this->addSql('ALTER TABLE resources CHANGE eid eid VARCHAR(255) DEFAULT NULL COMMENT \'企业id\', CHANGE passport_uid passport_uid VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE selfservice_registration_activity CHANGE pics pics TEXT');
        $this->addSql('ALTER TABLE user_signin_rules CHANGE days_required days_required  BIGINT NOT NULL COMMENT \'需要的天数\'');
        $this->addSql('ALTER TABLE wechat_weapp_customize_page ADD regionauth_id BIGINT DEFAULT 0 NOT NULL COMMENT \'区域id\', CHANGE page_type page_type VARCHAR(255) DEFAULT \'normal\' NOT NULL COMMENT \'页面类型 normal:普通页面 salesperson:导购首页 category:分类页 my:我的\'');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
}
